### ISSUE TITLE
Improve "No Appointments Found" information

### ISSUE THREAD

**Issue by harcod** [livgust/macovidvaccines.com#72]
Currently, when there is no availability the web site displays the simple message...

> No appointments found.

This is becoming a more common occurrence at this time.  We could add more information to educate and give hope to our visitor.

**Comment by harcod** [comment]
Suggestion:

> **No Appointments Found**
>
>This website scrapes data from other websites every 5 minutes and tells you what places currently are advertising available appointments for COVID vaccines.
>
>Mass vaccination locations have the most appointments and update their schedules every Thursday. Smaller locations offer fewer appointments but update their schedules daily.

**Comment by harcod** [comment]
> **_Visual presentation:_**

![image](https://user-images.githubusercontent.com/546007/108630074-0f122900-7431-11eb-8910-b7a73c784b40.png)

**Comment by livgust** [comment]
I like the idea of making it more visually explicit when we have no results. I'd suggest this copy:

> This website gathers data every minute from various COVID-19 vaccine distribution sites across Massachusetts. Currently, none are advertising any availability. Check back periodically for the most up-to-date information.

I don't love the last sentence I wrote but I'd rather not put information on when things might open up because it really can vary. For example, the state-sponsored sites on the Cape a few weeks ago went live on a Tuesday at 8 or 9 am.

**Comment by johnhawkinson** [comment]
I don't think we should make a claim about Thursdays. For one thing, it wasn't true of the Worcester/St. Vincent site that added 2,400 appointments over the weekend. And for another thing, the Commonwealth's promises notwithstanding, I don' think we can expect them to hold to that for the others, even if there weren't variable issues like cold chain transport and winterstorms affecting delivery.

**Comment by j256** [comment]
So if we say something like "none of the sites that we monitor" that would be better @johnhawkinson ?  Or add something like "Please check the state site for other alternatives" or something?

**Comment by johnhawkinson** [comment]
Sorry, @j256, I'm confused. I only spoke to the issue of
> Mass vaccination locations…update their schedules every Thursday

I don't follow what the issue I raised (duplicative of what Liv said 2 minutes before me, because our posts both crossed), has anything to do with limiting it to "sites that we monitor."

**Comment by harcod** [comment]
**RESET!**  Comment on this suggestion.

> [MACovidVaccines.com](https://MACovidVaccines.com) gathers data every minute from various COVID-19 vaccine distribution sites across Massachusetts. Currently, none of the sites that we monitor are currently advertising any availability.
>
>Check back occasionally for updated information.

**Comment by harcod** [comment]
Do we want to acknowledge that we don't index _everything_?  
We could consider referring them to VaxFinder (_don't shoot me_) by adding a 3rd paragraph.

> There may be additional vaccination locations that we do not currently have in our listing.  You could also check at [vaxfinder.mass.gov](https://vaxfinder.mass.gov)

**Comment by johnhawkinson** [comment]
>  We could consider referring them to VaxFinder (don't shoot me) by adding a 3rd paragraph.

Vaxfinder is already linked in the {|||} > Resources box, so clearly we're not averse to acknowledging their existence.
Probably should just make the text consistent?

**Comment by harcod** [comment]
![image](https://user-images.githubusercontent.com/546007/108638708-709cbc80-745e-11eb-8e5b-5cb1d6947994.png)

**Comment by harcod** [comment]
Here is the text in case you wanted to cut-and-paste a suggestion:

> **No Appointments Found**
> 
> MACovidVaccines.com gathers data every minute from various COVID-19 vaccine distribution sites across Massachusetts. Currently, none of the sites that we monitor are currently advertising any availability.
> 
> Check back occasionally for updated information.
> 
> There are two other websites for the state of Massachusetts that compile information on vaccine availability. They are:
> Vaccinate MA (volunteer-run)
> Vax Finder (state-run)
> 
> For more information on the vaccine rollout in Massachusetts, visit www.mass.gov/covid-19-vaccine.

**Comment by hshubin** [comment]
I took your suggestion and did some editing. The original and my edits appear below, along with comments about why I made the changes. (Do you care about the reasons?)

This is [the best resource for _writing_ online](https://www.nngroup.com/articles/how-people-read-online/). It’s based on how people _read_ online. The idea is that we don’t really read online; we’re more likely to just skim. So online text has to be as brief as possible, and make it easy to skim by using lists, bold, italics, etc.

_===Original text===_

**No Appointments Found**

MACovidVaccines.com gathers data every minute from various COVID-19 vaccine distribution sites across Massachusetts. Currently, none of the sites that we monitor are currently advertising any availability.

Check back occasionally for updated information.

There are two other websites for the state of Massachusetts that compile information on vaccine availability. They are:
• Vaccinate MA (volunteer-run)
 • Vax Finder (state-run)

For more information on the vaccine rollout in Massachusetts, visit www.mass.gov/covid-19-vaccine.


_=== Update ===_

**No Appointments Found**

None of the vaccine sites that we monitor currently have available appointments. This website gathers data every minute from COVID-19 vaccine sites across Massachusetts. 

Check back occasionally for updated information.

These websites may have have found appointments that we don’t have access to:
• Vaccinate MA (volunteer-run)
• Vax Finder (state-run)

For more information on the vaccine rollout in Massachusetts, visit www.mass.gov/covid-19-vaccine.

_=== Comments ===_

First paragraph:
- Switched the order of the two sentences. The first sentence now says why we're not showing availability.
- Took out the name of this website and put in “This website”. If there’s a link, people will click on it. Even though this is where they are, they might not recognize the name and wonder if that’s a place they should go. 
- Changed the end to be "have available appointments” instead of “advertising any availability”, because that’s the text that the toggle uses.
- Cut out some words.


Third paragraph:

- Took out "for the state of Massachusetts” because it’s mentioned in the 1st para. Took out a few words.
- Can you remove the blank line before the bulleted list? That will connect it better to the text that introduces it.
- Is the point of including the other two websites that they may have information we don’t have? (It seems so from some comments here.) If so, let’s say that explicitly.

**Comment by livgust** [comment]
> Currently, none of the sites that we monitor are currently advertising any availability.
Double "currently"s. I recommend keeping the first and ditching the second. 
IMO we definitely shouldn't send anyone to VaxFinder because they hook into _fewer_ locations than our website. VaccinateMA I believe has more locations but does more manual work (from what I hear) so their information may be outdated. Personally, since both are linked from the menu, I think we should leave out any redirects here. The link to the state rollout webpage is also linked in the menu.

So I guess I'm advocating for "added context, but still short & sweet."

**Comment by hshubin** [comment]
Taking out the links makes it shorter, which is good. Do we want to say "every minute" here? If you change that again, you'll have to remember to update it here. And I took out "occasionally", and joined the last two sentences into one paragraph.

**No Appointments Found**

None of the vaccine sites that we monitor currently have available appointments. This website gathers data every minute from COVID-19 vaccine sites across Massachusetts.

Check back for updated information. For more information on the vaccine rollout in Massachusetts, visit www.mass.gov/covid-19-vaccine.

**Comment by livgust** [comment]
Thanks @hshubin, I missed your prior comment :) your most recent version looks good to me!

**Comment by harcod** [comment]
![image](https://user-images.githubusercontent.com/546007/108640333-076d7700-7467-11eb-9a35-6f19067bed7c.png)

**Comment by hshubin** [comment]
I'd take out "occasionally" in the second paragraph. We can't say how often they should check (every minute!), so I'd leave it out. Unless there's a better word?
