### ISSUE TITLE
Unit Test Fails on "No Appointments Found"

### ISSUE THREAD

**Issue by harcod** [livgust/macovidvaccines.com#79]
With the introduction new code in PR #75, there is a failed test in CovidAppointmentTable.test.js at line 76 (test named "when the api endpoint can not be reached")

There in this case there are 2 "role=alert" divs in the file.  Is this causing the failure?

**Comment by livgust** [comment]
Yes, that'd be it. The test that's looking for the "try again later" alert (when our endpoint fails, which it never does *knock on wood*) is also noticing the alert you added, which makes sense, because when we fail we also show 0 results.

Potential solutions:
1) be OK with 2 alerts, and update tests
2) don't show the "no results" messaging you added if there's a failure

In any case I think it would also be nice to update the display of the error message, which was added for testing purposes so it doesn't have a real "UI."

**Comment by livgust** [comment]
I did a quick fix in PR #75 but I think that we could do something a little nicer.
