### ISSUE TITLE
Make individual site restrictions apparent

### ISSUE THREAD

**Issue by livgust** [livgust/macovidvaccines.com#9]
Some sites are only open to residents of certain towns, etc. Most of that information is in the "More Information" section, which is collapsed by default. We should either guess that there is a restriction by doing some regex matches or something, OR tag them on the back-end with restrictions manually and surface that on the front-end.

If we go with the latter, please create an issue for the corresponding back-end task in the scraper repo.

**Comment by tom-ricci** [comment]
Most sites seem to use markdown and wrap restrictions in ***, but some of them also use it for other things as well or not use it at all. Tagging would probably be the best way to go but we could guess for the ones which have markdown or some other indicators

**Comment by harcod** [comment]
We are hiding the "More Information" so that people can click on the "Sign Up" link without reading it.  Then they get sent directly to the clinic sign up page without ever seeing this information which might exclude them based on things such as residency.

What if we simplify the displayed information down to the bare minimum? **Number of slots** and **Vaccine Type**.  Everything else (including the _Sign Up_ button) gets hidden beneath the _more information accordian_.

In this way, we are at least showing all of the information to the patient prior to them clicking on the "Sign Up" button.

Here is the version that I have right now.

**Accordian Collapsed (Default on page load):**
![image](https://user-images.githubusercontent.com/546007/107971160-1c866980-6f80-11eb-85cc-0175e0606301.png)

**Accordian Expanded:**
![image](https://user-images.githubusercontent.com/546007/107971268-4475cd00-6f80-11eb-9177-3db1f3f3ed05.png)

**Comment by livgust** [comment]
#37
